# spring:
#   application:
#     name: license-service
#   profiles:
#     active:
#     - dev
    
management:
  endpoints:
    web:
      base-path: /
      exposure:
        include: "*"
        exclude:
         - beans
  endpoint:
    health:
      show-details: always			
  health:
    diskspace:
      enabled: true
server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ostock_dev
    username: postgres
    password: "{cipher}afb2d19f737cc1bbdbe30a195667415e3c0159ddf88e2023df9cdd28a8260b3d"
